services:
  redis:
    network_mode: host
    ports: []

  web:
    build:
      network: host
    network_mode: host
    environment:
      REDIS_URL: redis://127.0.0.1:6379/0
    ports: []

  worker:
    build:
      network: host
    network_mode: host
    environment:
      REDIS_URL: redis://127.0.0.1:6379/0

  cli:
    build:
      network: host
    network_mode: host
